[package]
name = "opendots-automation"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
opendots-db = { path = "../db" }
opendots-shared = { path = "../shared" }
dashmap.workspace = true
dirs.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-cron-scheduler.workspace = true
uuid.workspace = true
